---
# tasks file for dotfiles
- name: Install dependencies
  package: name={{ item }} state=latest
  with_items:
    - vim-nox
    - git
    - zsh
    - screen
    - python-pip

- name: Check for previous existence of dotfiles
  stat: path=~/.dotfiles
  register: dotfiles_installed

- name: Clone dotfiles repo
  git: repo=https://github.com/dklight/dotfiles.git
       dest=~/.dotfiles
       track_submodules=yes
  when: not dotfiles_installed.stat.exists
